arb-dir: lib/l10n
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/l10n/desiredFileName.txt
synthetic-package: false
output-dir: lib/l10n/generated